// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110000746_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("OfficerBadgeNumberSeq", "dbo");

            modelBuilder.Entity("Domain.Common.Abstractions.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Domain.Cases.CaseParticipant", b =>
                {
                    b.HasBaseType("Domain.Common.Abstractions.Entity");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("CaseId");

                    b.HasIndex("CitizenId");

                    b.ToTable("CaseParticipants", (string)null);
                });

            modelBuilder.Entity("Domain.Cases.Evidences.Evidence", b =>
                {
                    b.HasBaseType("Domain.Common.Abstractions.Entity");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectionMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CaseId");

                    b.ToTable("Evidences", (string)null);
                });

            modelBuilder.Entity("Domain.Cases.Witnesses.Witness", b =>
                {
                    b.HasBaseType("Domain.Common.Abstractions.Entity");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Statements")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasIndex("CaseId");

                    b.HasIndex("CitizenId");

                    b.ToTable("Witnesses", (string)null);
                });

            modelBuilder.Entity("Domain.Citizens.Citizen", b =>
                {
                    b.HasBaseType("Domain.Common.Abstractions.Entity");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .IsFixedLength();

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Citizen_FullName");

                    b.ToTable("Citizens", null, t =>
                        {
                            t.HasCheckConstraint("CK_DateOfBirth", "DateOfBirth <= GETUTCDATE() and DateOfBirth > DateAdd(YEAR, -110, GETUTCDATE())");
                        });
                });

            modelBuilder.Entity("Domain.Common.Abstractions.AuditableEntity", b =>
                {
                    b.HasBaseType("Domain.Common.Abstractions.Entity");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Domain.Officers.Departments.Department", b =>
                {
                    b.HasBaseType("Domain.Common.Abstractions.Entity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("Varchar");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Domain.Officers.Officer", b =>
                {
                    b.HasBaseType("Domain.Common.Abstractions.Entity");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<Guid>("InStateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("CHAR(15)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InStateId");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Officer_FullName");

                    b.ToTable("Officers", (string)null);
                });

            modelBuilder.Entity("Domain.Officers.OfficerBadgeNumber", b =>
                {
                    b.HasBaseType("Domain.Common.Abstractions.Entity");

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("OfficerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("OfficerId")
                        .IsUnique()
                        .HasFilter("[OfficerId] IS NOT NULL");

                    b.ToTable("OfficerBadgeNumbers", (string)null);
                });

            modelBuilder.Entity("Domain.States.State", b =>
                {
                    b.HasBaseType("Domain.Common.Abstractions.Entity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("CHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(30)");

                    b.ToTable("States", (string)null);
                });

            modelBuilder.Entity("Domain.Users.UserLoginAudit", b =>
                {
                    b.HasBaseType("Domain.Common.Abstractions.Entity");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("VARCHAR")
                        .IsFixedLength();

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LoginTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.HasIndex("UserId");

                    b.ToTable("UserLoginAudits", (string)null);
                });

            modelBuilder.Entity("Domain.Cases.Case", b =>
                {
                    b.HasBaseType("Domain.Common.Abstractions.AuditableEntity");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar(550)");

                    b.Property<string>("FinalReport")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("IncidentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("InvestigationStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProgressReport")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasIndex("IncidentDate")
                        .HasDatabaseName("IX_IncidentDate");

                    b.ToTable("Cases", null, t =>
                        {
                            t.HasCheckConstraint("CK_ClosedAt", "ClosedAt > IncidentDate and InvestigationStartedAt is null or ClosedAt > InvestigationStartedAt and ClosedAt <= GETUTCDATE()");

                            t.HasCheckConstraint("CK_IncidentDate", "IncidentDate < InvestigationStartedAt and IncidentDate <= GETUTCDATE()");

                            t.HasCheckConstraint("CK_InvestigationStartedAt", "IncidentDate is null or InvestigationStartedAt > IncidentDate and ClosedAt is null");
                        });
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.HasBaseType("Domain.Common.Abstractions.AuditableEntity");

                    b.Property<int>("FailedLoginAttemptsCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("LockTime")
                        .HasColumnType("time");

                    b.Property<Guid>("OfficerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.HasIndex("OfficerId")
                        .IsUnique()
                        .HasFilter("[OfficerId] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Cases.CaseParticipant", b =>
                {
                    b.HasOne("Domain.Cases.Case", "Case")
                        .WithMany("Participants")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Citizens.Citizen", "CitizenInfo")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("CitizenInfo");
                });

            modelBuilder.Entity("Domain.Cases.Evidences.Evidence", b =>
                {
                    b.HasOne("Domain.Cases.Case", "Case")
                        .WithMany("Evidences")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Domain.Cases.Witnesses.Witness", b =>
                {
                    b.HasOne("Domain.Cases.Case", "WitnessedForCase")
                        .WithMany("Witnesses")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Citizens.Citizen", "CitizenInfo")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CitizenInfo");

                    b.Navigation("WitnessedForCase");
                });

            modelBuilder.Entity("Domain.Officers.Officer", b =>
                {
                    b.HasOne("Domain.Officers.Departments.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.States.State", "InState")
                        .WithMany()
                        .HasForeignKey("InStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("InState");
                });

            modelBuilder.Entity("Domain.Officers.OfficerBadgeNumber", b =>
                {
                    b.HasOne("Domain.Officers.Officer", "Officer")
                        .WithOne("BadgeNumber")
                        .HasForeignKey("Domain.Officers.OfficerBadgeNumber", "OfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("Domain.Users.UserLoginAudit", b =>
                {
                    b.HasOne("Domain.Users.User", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.HasOne("Domain.Officers.Officer", "OfficerInfo")
                        .WithOne("UserInfo")
                        .HasForeignKey("Domain.Users.User", "OfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficerInfo");
                });

            modelBuilder.Entity("Domain.Officers.Officer", b =>
                {
                    b.Navigation("BadgeNumber");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("Domain.Cases.Case", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("Participants");

                    b.Navigation("Witnesses");
                });
#pragma warning restore 612, 618
        }
    }
}
